"""add authentication fields to users

Revision ID: d9db4a4fe5c1
Revises: 28f58f533f39
Create Date: 2026-09-23 20:36:42.199335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9db4a4fe5c1'
down_revision: Union[str, Sequence[str], None] = '28f58f533f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'usuarios',
        sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default='')
    )

    op.add_column(
        'usuarios',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###
